# Generated by Django 4.1.6 on 2023-03-05 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('ID_Facturas', models.AutoField(primary_key=True, serialize=False)),
                ('Monto_Solicitado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Tasa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Cuotas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Cuotas_Mensuales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Monto_Pagar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Capital', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Interes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Fecha', models.DateField()),
                ('Nombre_Apellido', models.CharField(max_length=150)),
                ('Telefono', models.CharField(max_length=15, null=True)),
                ('Cedula', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('ID_USUARIO', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Apellido', models.CharField(max_length=150)),
                ('Telefono', models.CharField(max_length=15, null=True)),
                ('Cedula', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialFacturas',
            fields=[
                ('ID_HistorialFactura', models.AutoField(primary_key=True, serialize=False)),
                ('Monto_Solicitado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Tasa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Cuotas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Cuotas_Mensuales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Monto_Pagar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Capital', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Interes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Fecha', models.DateField()),
                ('Nombre_Apellido', models.CharField(max_length=150)),
                ('Telefono', models.CharField(max_length=15, null=True)),
                ('Cedula', models.CharField(max_length=20, null=True)),
                ('Factura_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackendAPI.facturas')),
                ('Usuario_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackendAPI.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='facturas',
            name='Usuario_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackendAPI.usuario'),
        ),
    ]
